apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
data:
  config.json: |
    {
      "storage": {
        "rootDirectory": "/tmp/zot"
      },
      "http": {
        "auth": {
          "htpasswd": {
            "path": "/secret/htpasswd"
          }
        },
        "tls": {
          "cert": "/etc/zot/certs/tls.crt",
          "key": "/etc/zot/certs/tls.key"
        },
        "accessControl": {
          "repositories": {
            "**": {
              "policies": [
                {
                  "users": ["fleet-ci"],
                  "actions": ["read", "create", "update", "delete"]
                },
                {
                  "users": ["fleet-ci-reader"],
                  "actions": ["read"]
                },
                {
                  "users": ["fleet-ci-no-deleter"],
                  "actions": ["read", "create"]
                }
              ],
              "defaultPolicy": []
            }
          }
        },
        "address": "0.0.0.0",
        "port": 8082
      },
      "log": {
        "level": "debug"
      },
      "extensions": {
        "ui": {
          "enable": true
        },
        "search": {
          "enable": true
        }
      }
    }
